### PR TITLE
Attempt to fix binary downloads for scala native

### LINKED ISSUE #131: ScalaNative: Unable to download binary files
When using sttp with ScalaNative, I'm attempting to download a JAR from a URL:

```scala
sttp.get(jar).response(asFile(outputFile)).send().unsafeBody
```
The output of `outputFile` is a 5 byte file.  The output to the console is (which should be another bug as there doesn't seem to be a way to turn it off):

```
Downloading http://repo1.maven.org/maven2/com/outr/jefe-runner_2.12/1.2.4/jefe-runner_2.12-1.2.4.jar...
*   Trying 151.101.48.209...
* TCP_NODELAY set
* Connected to repo1.maven.org (151.101.48.209) port 80 (#0)
> GET /maven2/com/outr/jefe-runner_2.12/1.2.4/jefe-runner_2.12-1.2.4.jar HTTP/1.1
Host: repo1.maven.org
Accept: */*
Accept-Encoding: gzip, deflate

< HTTP/1.1 200 OK
< ETag: "be50aa1ecb13b6ec56baa9f3f0eb6fa3"
< Content-Type: application/java-archive
< Last-Modified: Mon, 23 Apr 2018 18:48:49 GMT
< X-Checksum-MD5: be50aa1ecb13b6ec56baa9f3f0eb6fa3
< X-Checksum-SHA1: 6251244a4a38c1ec1b4ccdb784abf897e27afd63
< Via: 1.1 varnish
< Content-Length: 23591
< Accept-Ranges: bytes
< Date: Tue, 24 Jul 2018 20:27:51 GMT
< Via: 1.1 varnish
< Age: 140
< Connection: keep-alive
< X-Served-By: cache-iad2128-IAD, cache-dfw18645-DFW
< X-Cache: HIT, HIT
< X-Cache-Hits: 1, 1
< X-Timer: S1532464072.507182,VS0,VE1
< 
* Connection #0 to host repo1.maven.org left intact
```

### PR DESCRIPTION
**Pull request by Pask423**
closes #131

### CODE REVIEW

File: core/src/main/scala/sttp/client3/RequestT.scala [hunk 1]
```diff
@@ -431,9 +431,11 @@ class SpecifyAuthScheme[U[_], T, -R](hn: String, rt: RequestT[U, T, R], digestTa
...
+// TODO replace with tag
 case class RequestOptions(
     followRedirects: Boolean,
     readTimeout: Duration,
     maxRedirects: Int,
-    redirectToGet: Boolean
-)
\ No newline at end of file
+    redirectToGet: Boolean,
+    binaryFile: Option[String] = None
```
Comment (adamw) [inline core/src/main/scala/sttp/client3/RequestT.scala:440]: I'm not sure what is the purpose of this - do you want to determine if the response should be saved as a file? If so, maybe we can examine `ResponseAs`?

**Comment by Pask423** [comment]
closes #131

File: core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala [hunk 2]
```diff
@@ -82,12 +82,26 @@ trait SyncHttpTestExtensions {
 
   "download file" - {
 
-    "download a binary file using asFile" in {
-      withTemporaryNonExistentFile { file =>
-        val req = basicRequest.get(uri"$endpoint/download/binary").response(asFile(file))
-        val resp = req.send(backend)
-        md5FileHash(resp.body.right.get).map { _ shouldBe binaryFileMD5Hash }
-      }
+    // TODO this test do not verify actual downloaded file
```
Comment (adamw) [inline core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: it checks the md5, so it does?

File: core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala [hunk 3]
```diff
@@ -57,45 +55,73 @@ abstract class AbstractCurlBackend[F[_]](monad: MonadError[F], verbose: Boolean)
...
+          setRequestBody(curl, request.body)
+          responseMonad.flatMap(lift(curl.perform)) { _ =>
+            curl.info(ResponseCode, spaces.httpCode)
+            val httpCode = StatusCode((!spaces.httpCode).toInt)
+            if (headers.ptr != null) headers.ptr.free()
+            multiPartHeaders.foreach(_.ptr.free())
+            free(spaces.httpCode.asInstanceOf[Ptr[CSignedChar]])
+            fclose(outputFilePtr)
+            curl.cleanup()
+            val responseMetadata = ResponseMetadata(httpCode, "", List.empty)
```
Comment (adamw) [inline core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala:74]: can't we get the response headers here?

File: core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala (hunk 2 above)
Comment (Pask423) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: so maybe my description is incorrect as our binary file from test was not saved properly while tests was passing

File: core/src/main/scalanative/sttp/client3/internal/BinaryFileHelper.scala [hunk 4]
```diff
@@ -0,0 +1,19 @@
+package sttp.client3.internal
+
+import sttp.client3.{MappedResponseAs, ResponseAs, ResponseAsFile, ResponseAsFromMetadata}
+
+object BinaryFileHelper {
```
Comment (adamw) [inline core/src/main/scalanative/sttp/client3/internal/BinaryFileHelper.scala:5]: FileHelper? Nothing specific to binary here :)

File: core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala [hunk 5]
```diff
@@ -57,45 +55,73 @@ abstract class AbstractCurlBackend[F[_]](monad: MonadError[F], verbose: Boolean)
...
-            code = httpCode,
-            statusText = statusText,
-            headers = responseHeaders,
-            history = Nil,
-            request = request.onlyMetadata
-          )
-        }
+      BinaryFileHelper.getFilePath(request.response) match {
+        case Some(file) =>
+          val outputPath = file.toPath.toString
```
Comment (adamw) [inline core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala:60]: maybe extract two methods with the two implementations?

File: core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala (hunk 2 above)
Comment (adamw) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: hm that's weird - how did the md5 match then? ;) I guess we can keep both tests

Comment (adamw) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: ah, maybe `resp.body.right.get` was `None`?

**Comment by adamw** [comment]
Looks good :)

File: core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala (hunk 2 above)
Comment (Pask423) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: I will check on current master give me some time

File: core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala (hunk 3 above)
Comment (Pask423) [reply core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala:74]: nope as they were written with `curl.option(HeaderData, spaces.headersResp)` which we cannot set with current setting

File: core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala (hunk 2 above)
Comment (Pask423) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: Yes you are right - to a degree, resp.body.right.get is good but `md5FileHash(resp.body.right.get)` is empty

File: core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala (hunk 3 above)
Comment (Pask423) [reply core/src/main/scalanative/sttp/client3/AbstractCurlBackend.scala:74]: at least with reasonable effort it may be possible somehow with `HEADERFUNCTION` and `HEADERDATA`  but it will require creation of another `wdFunc`-like function and I am not sure if it will work

File: core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala (hunk 2 above)
Comment (Pask423) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala:85]: In fact there is some strange error with md5Hash function -> it always return empty string

Comment (Pask423) [reply core/src/test/scalanative/sttp/client3/testing/SyncHttpTestExtensions.scala]: https://github.com/scala-native/scala-native/pull/2175

**Comment by adamw** [comment]
Looks good! Would be great to have the headers as well, but if that's not possible, let's merge as-is :)
