### PR TITLE
Armeria retry

### LINKED ISSUE #1616: Armeria backend returns previous failure result on retry
This behavior showed up in a commercial project, when we switched to Cats Effect 3. We replaced `async-http-client-backend-cats-ce2` with `armeria-backend-cats`, and some of our tests started to fail. It seems that recursive `task.recoverWith` calls keep getting the same HTTP error and eventually exhaust all retries, but the server receives only one request.

After switching from Armeria to FS2 IO backend our tests work again as expected. Maybe Armeria itself is somehow caching responses?

I created an example test showcasing this issue:  https://github.com/kciesielski/sttp-armeria-showcase

In `SttpRetrySpec` switch between `newBackend` and `newBackend2` and notice the difference.

### PR DESCRIPTION
**Pull request by Pask423**
Closes #1616 
In my opinion the problem was that a part of send in `AbstractArmeriaBackend.scala` was not wrapped by F context and thus was executing only once for all the retries.

### CODE REVIEW

File: armeria-backend/cats/src/test/scala/sttp/client3/armeria/cats/ArmeriaCatsHttpTest.scala [hunk 1]
```diff
@@ -16,6 +26,66 @@ class ArmeriaCatsHttpTest extends HttpTest[IO] with CatsTestBase {
     }
   }
 
+  val port = 8080
```
Comment (Pask423) [inline armeria-backend/cats/src/test/scala/sttp/client3/armeria/cats/ArmeriaCatsHttpTest.scala:29]: Maybe it will be beneficial to make this test usable in all backends

File: armeria-backend/src/main/scala/sttp/client3/armeria/AbstractArmeriaBackend.scala [hunk 2]
```diff
@@ -59,7 +59,7 @@ abstract class AbstractArmeriaBackend[F[_], S <: Streams[S]](
   override def responseMonad: MonadError[F] = monad
 
   override def send[T, R >: SE](request: Request[T, R]): F[Response[T]] =
-    adjustExceptions(request)(execute(request))
+    monad.unit(request).flatMap(r => adjustExceptions(request)(execute(r)))
```
Comment (adamw) [inline armeria-backend/src/main/scala/sttp/client3/armeria/AbstractArmeriaBackend.scala:62]: ah, good catch! though for this purpose there's `monad.suspend`

File: armeria-backend/cats/src/test/scala/sttp/client3/armeria/cats/ArmeriaCatsHttpTest.scala [hunk 3]
```diff
@@ -16,6 +26,66 @@ class ArmeriaCatsHttpTest extends HttpTest[IO] with CatsTestBase {
...
+      )
+      .respond(
+        response()
+          .withStatusCode(code)
+      )
+  }
+
+  "retry test" - {
+    "should call the HTTP server twice" in {
+      var mockServer: ClientAndServer = null
```
Comment (adamw) [inline armeria-backend/cats/src/test/scala/sttp/client3/armeria/cats/ArmeriaCatsHttpTest.scala:63]: hm maybe we can do the same with our stub backend?

File: armeria-backend/src/main/scala/sttp/client3/armeria/AbstractArmeriaBackend.scala (hunk 2 above)
Comment (kciesielski) [reply armeria-backend/src/main/scala/sttp/client3/armeria/AbstractArmeriaBackend.scala:62]: 🎖️
