### PR TITLE
Fix native on ARM (Macs)

### LINKED ISSUE #1668: native: Command failed with status URL_MALFORMAT / COULDNT_RESOLVE_HOST
I am testing `scala-cli` with `sttp` and always get one of these two errors reported

`arm64 mac`

```scala
//> using scala "3.2.1"
//> using lib "com.softwaremill.sttp.client3::core::3.8.5"

import sttp.client3.quick.*

@main def httptest() =
  val url = uri"http://httpbin.org/ip"
  val res = simpleHttpClient.send(quickRequest.get(url))
  println(res.body)
```

```
> scala-cli test.scala --platform native
Compiling project (Scala 3.2.1, Scala Native)
Compiled project (Scala 3.2.1, Scala Native)
[info] Linking (1113 ms)
[info] Discovered 1557 classes and 11448 methods
[info] Optimizing (debug mode) (2126 ms)
[info] Generating intermediate code (1158 ms)
[info] Produced 10 files
[info] Compiling to native code (1980 ms)
[info] Total (6507 ms)
java.lang.RuntimeException: Command failed with status URL_MALFORMAT
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at sttp.client3.AbstractCurlBackend.lift(Unknown Source)
	at sttp.client3.AbstractCurlBackend.handleBase(Unknown Source)
	at sttp.client3.AbstractCurlBackend.send$$anonfun$1(Unknown Source)
	at sttp.client3.AbstractCurlBackend$$Lambda$1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at sttp.client3.AbstractCurlBackend.send(Unknown Source)
	at sttp.client3.FollowRedirectsBackend.sendWithCounter(Unknown Source)
	at sttp.client3.FollowRedirectsBackend.send(Unknown Source)
	at sttp.client3.SimpleHttpClient.send(Unknown Source)
	at test$package$.httptest(Unknown Source)
	at httptest.main(Unknown Source)
	at <none>.main(Unknown Source)
```

```
> scala-cli test.scala --platform native
java.lang.RuntimeException: Command failed with status COULDNT_RESOLVE_HOST
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at sttp.client3.AbstractCurlBackend.lift(Unknown Source)
	at sttp.client3.AbstractCurlBackend.handleBase(Unknown Source)
	at sttp.client3.AbstractCurlBackend.send$$anonfun$1(Unknown Source)
	at sttp.client3.AbstractCurlBackend$$Lambda$1.apply(Unknown Source)
	at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
	at sttp.client3.AbstractCurlBackend.send(Unknown Source)
	at sttp.client3.FollowRedirectsBackend.sendWithCounter(Unknown Source)
	at sttp.client3.FollowRedirectsBackend.send(Unknown Source)
	at sttp.client3.SimpleHttpClient.send(Unknown Source)
	at test$package$.httptest(Unknown Source)
	at httptest.main(Unknown Source)
	at <none>.main(Unknown Source)
```

This works correctly when running on the JVM

```
> scala-cli test.scala
Compiling project (Scala 3.2.1, JVM)
Compiled project (Scala 3.2.1, JVM)
{
  "origin": "78.23.##.#"
}
```

This is a similar issue to the previously closed https://github.com/softwaremill/sttp/issues/376
https://gitter.im/scala-native/scala-native?at=5de7dc18c3d6795b9f2148c2

### PR DESCRIPTION
**Pull request by szymon-rd**
Fix #1668

Something was going wrong with the way libcurl exposes API functions with varargs, and how scala native was calling them on ARM Macs. So I added an interface in between. (thanks @WojciechMazur)

### CODE REVIEW

File: core/src/main/scalanative/sttp/client4/curl/internal/CCurl.scala [hunk 1]
```diff
@@ -25,23 +25,29 @@ private[curl] object libcurlPlatformCompat {
...
 @extern
 private[curl] trait CCurl {
+  @name("sttp_curl_setopt_int")
+  def setoptInt(handle: Ptr[Curl], option: CInt, parameter: Int): CInt = extern
+
+  @name("sttp_curl_setopt_long")
+  def setoptLong(handle: Ptr[Curl], option: CInt, parameter: Long): CInt = extern
+
+  @name("sttp_curl_setopt_pointer")
+  def setoptPtr(handle: Ptr[Curl], option: CInt, parameter: Ptr[_]): CInt = extern
```
Comment (WojciechMazur) [inline core/src/main/scalanative/sttp/client4/curl/internal/CCurl.scala:35]: This 3 functions can have regular `setopt` name, `@name` annotations works as Scala Native specific `@targetName` annotation for extern symbols.

File: core/src/main/resources/scala-native/ffi.c [hunk 2]
```diff
@@ -0,0 +1,7 @@
+#include <curl/curl.h>
```
Comment (WojciechMazur) [inline core/src/main/resources/scala-native/ffi.c:1]: The CI seems to be failing because it cannot find `libcurl` library at linking. It seems, like the `CCurl.libcurlPlatformCompat.instance` was never referenced in projects not testing/using curl. To fix it we can introduce a compiletime guard using macro preprocessor definitions. For that we can wrap this file content in 
```c 
#if defined(STTP_CURL_FFI)
#include <curl/curl.h> 
...
#endif
``` 

and add `@define("STTP_CURL_FFI")` to symbols that use `@link("curl")` or `@link("libcurl")`. 
At this point this C file content would be compiled only when curl definitions would be referenced. See https://github.com/scala-native/scala-native/pull/3427
Unfortunately, it seems like `@define` annotation was not backported from main branch to 0.4.x, I'll make try to include it and release 0.4.18 this weekend.

**Review by WojciechMazur — COMMENTED** [review]
LGTM, but we might need to wait for 0.4.18 to make the bindings portable

**Comment by adamw** [comment]
If you rebase, the JS build problems should get fixed

**Comment by lbialy** [comment]
bumping for subscription

File: core/src/main/resources/scala-native/ffi.c (hunk 2 above)
Comment (kciesielski) [reply core/src/main/resources/scala-native/ffi.c:1]: @WojciechMazur I'm updating this PR to scala-native 0.5.1 now, I guess this is still relevant?

**Comment by kciesielski** [comment]
@szymon-rd I switched scala-native to 0.5.1 and applied a few more updates, could you verify if this PR fixes the ARM issue now?

**Comment by WojciechMazur** [comment]
Seems to be building fine on ARM (MacOS M1), but I'm experiencing a deadlocks in some tests, eg. in the redirects. What's strange is the fact that I can observe it not only in this PR, but also on GitPod env (x64) on both this PR and main branch. I'm not really sure why. After attaching debugger the libcurl seems to be stuck in `fread` functions, although it seems like it should be done already (it was able to process the headers, there should be no body?)

**Comment by szymon-rd** [comment]
I don't have access to ARM Mac now so sadly I am not able to verify it. @kciesielski

**Comment by WojciechMazur** [comment]
I've figured out the issues with the deadlocks - the empty POST request in some (newer?) versions of curl by default might wait for input on stdin. To prevent that we should set `PostFields` options with empty input explicitly. After applying this change I was able to successfully run all tests on MacOS M1. 
I've tried to setup a CI job for sttp to use macos-14 runner - these are using ARM64 arch on M1 chips, however there are some issues when using native libraries. For some reason it expects x86_64 libs, instead of ARM64, it's really strange. 

Anyway I here's a fix and a small cleanup. I've cannot push it directly to the PR. @kciesielski can you commit this patch to speed up merging this PR?

```patch
diff --git a/core/src/main/scalanative/sttp/client4/curl/AbstractCurlBackend.scala b/core/src/main/scalanative/sttp/client4/curl/AbstractCurlBackend.scala
index 337f9a266..d7e657bc7 100644
--- a/core/src/main/scalanative/sttp/client4/curl/AbstractCurlBackend.scala
+++ b/core/src/main/scalanative/sttp/client4/curl/AbstractCurlBackend.scala
@@ -117,7 +117,7 @@ abstract class AbstractCurlBackend[F[_]](_monad: MonadError[F], verbose: Boolean
     curl.option(HeaderData, spaces.headersResp)
     curl.option(Url, request.uri.toString)
     setMethod(curl, request.method)
-    setRequestBody(curl, request.body)
+    setRequestBody(curl, request.body, request.method)
     monad.flatMap(perform(curl)) { _ =>
       curl.info(ResponseCode, spaces.httpCode)
       val responseBody = fromCString((!spaces.bodyResp)._1)
@@ -157,7 +157,7 @@ abstract class AbstractCurlBackend[F[_]](_monad: MonadError[F], verbose: Boolean
     curl.option(WriteData, outputFilePtr)
     curl.option(Url, request.uri.toString)
     setMethod(curl, request.method)
-    setRequestBody(curl, request.body)
+    setRequestBody(curl, request.body, request.method)
     monad.flatMap(perform(curl)) { _ =>
       curl.info(ResponseCode, spaces.httpCode)
       val httpCode = StatusCode((!spaces.httpCode).toInt)
@@ -195,7 +195,7 @@ abstract class AbstractCurlBackend[F[_]](_monad: MonadError[F], verbose: Boolean
     lift(m)
   }
 
-  private def setRequestBody(curl: CurlHandle, body: GenericRequestBody[R])(implicit
+  private def setRequestBody(curl: CurlHandle, body: GenericRequestBody[R], method: Method)(implicit
       ctx: Context
   ): F[CurlCode] = {
     implicit val z = ctx.zone
@@ -223,7 +223,9 @@ abstract class AbstractCurlBackend[F[_]](_monad: MonadError[F], verbose: Boolean
       case StreamBody(_) =>
         monad.error(new IllegalStateException("CurlBackend does not support stream request body"))
       case NoBody =>
-        monad.unit(CurlCode.Ok)
+        // POST with empty body might wait for the input on stdin
+        if (method.is(Method.POST)) lift(curl.option(PostFields, c""))
+        else monad.unit(CurlCode.Ok)
     }
   }
 
diff --git a/core/src/main/scalanative/sttp/client4/curl/internal/CurlApi.scala b/core/src/main/scalanative/sttp/client4/curl/internal/CurlApi.scala
index 16f592e6c..5b5a17e92 100644
--- a/core/src/main/scalanative/sttp/client4/curl/internal/CurlApi.scala
+++ b/core/src/main/scalanative/sttp/client4/curl/internal/CurlApi.scala
@@ -4,7 +4,6 @@ import sttp.client4.curl.internal.CurlCode.CurlCode
 import sttp.client4.curl.internal.CurlInfo.CurlInfo
 import sttp.client4.curl.internal.CurlOption.CurlOption
 
-import scala.scalanative.runtime.Boxes
 import scala.scalanative.unsafe.{Ptr, _}
 import scala.scalanative.unsigned._
 import java.nio.charset.StandardCharsets
@@ -29,22 +28,22 @@ private[client4] object CurlApi {
     def cleanup(): Unit = CCurl.cleanup(handle)
 
     def option(option: CurlOption, parameter: String)(implicit z: Zone): CurlCode =
-      CurlCode(CCurl.setoptPtr(handle, option.id, toCString(parameter, StandardCharsets.UTF_8)))
+      this.option(option, toCString(parameter, StandardCharsets.UTF_8))
 
-    def option(option: CurlOption, parameter: Long)(implicit z: Zone): CurlCode =
+    def option(option: CurlOption, parameter: Long): CurlCode =
       CurlCode(CCurl.setoptLong(handle, option.id, parameter))
 
-    def option(option: CurlOption, parameter: Int)(implicit z: Zone): CurlCode =
+    def option(option: CurlOption, parameter: Int): CurlCode =
       CurlCode(CCurl.setoptInt(handle, option.id, parameter))
 
-    def option(option: CurlOption, parameter: Boolean)(implicit z: Zone): CurlCode =
-      CurlCode(CCurl.setoptInt(handle, option.id, if (parameter) 1 else 0))
+    def option(option: CurlOption, parameter: Boolean): CurlCode =
+      this.option(option, if (parameter) 1 else 0)
 
     def option(option: CurlOption, parameter: Ptr[_]): CurlCode =
       CurlCode(CCurl.setoptPtr(handle, option.id, parameter))
 
-    def option[FuncPtr <: CFuncPtr](option: CurlOption, parameter: FuncPtr)(implicit z: Zone): CurlCode =
-      CurlCode(CCurl.setoptPtr(handle, option.id, Boxes.boxToPtr[Byte](Boxes.unboxToCFuncPtr0(parameter))))
+    def option(option: CurlOption, parameter: CFuncPtr): CurlCode =
+      this.option(option, CFuncPtr.toPtr(parameter))
 
     def info(curlInfo: CurlInfo, parameter: Long)(implicit z: Zone): CurlCode = {
       val lPtr = alloc[Long](sizeof[Long])

```

**Comment by kciesielski** [comment]
Sure, I'm on it. Thanks a lot for this investigation @WojciechMazur!
