### PR TITLE
Fix resource leak for HttpClient-based backends on cancellation

### LINKED ISSUE #1987: ReadException "too many concurrent streams"
Hi i am running a service which makes lots of calls to some other service, lets say 10 calls per second.

The service runs properly but eventually there are periods when it starts to crash with

```
sttp.client3.SttpClientException$ReadException: Exception when sending request: POST https://xxxxx
	at sttp.client3.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:25)
	at sttp.client3.SttpClientExceptionExtensions.defaultExceptionToSttpClientException$(SttpClientExceptionExtensions.scala:9)
	at sttp.client3.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:24)
	at sttp.client3.HttpClientAsyncBackend.adjustExceptions$$anonfun$1(HttpClientAsyncBackend.scala:147)
	at sttp.client3.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:35)
	at sttp.client3.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:34)
	at zio.ZIO.tryRescue$1$$anonfun$1(ZIO.scala:359)
	at scala.util.Either.fold(Either.scala:190)
	at zio.ZIO.tryRescue$1(ZIO.scala:359)
	at zio.ZIO.catchSome$$anonfun$1(ZIO.scala:361)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1121)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
Caused by: java.io.IOException: too many concurrent streams
	at java.net.http/jdk.internal.net.http.Http2Connection.reserveStream(Http2Connection.java:484)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:106)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:369)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:553)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:406)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:398)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:409)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:342)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
```

```
  lazy val sttpV = "3.8.+"

        "com.softwaremill.sttp.client3" %% "core" % sttpV,
      "com.softwaremill.sttp.client3" %% "zio" % sttpV,
```

Also its a POST request with some timeout a json body and some auth headers

in sttp code i do see
```
case e: java.io.IOException                   => Some(new ReadException(request, e))
```
and also from the stack trace one can see its an IO exception with `too many concurrent streams`

Any obvious solution ?

### PR DESCRIPTION
**Pull request by adamw**
Closes #1987

### CODE REVIEW

File: effects/zio/src/main/scalajvm/sttp/client4/httpclient/zio/HttpClientZioBackend.scala [hunk 1]
```diff
@@ -52,12 +67,19 @@ class HttpClientZioBackend private (
...
     FlowAdapters.toPublisher(p).toZIOStream().mapConcatChunk { list =>
       val a = Chunk.fromJavaIterable(list).flatMap(_.safeRead()).toArray
       ByteArray(a, 0, a.length)
     }
 
+  override protected def cancelLowLevelBody(p: Publisher[ju.List[ByteBuffer]]): Unit = cancelPublisher(p)
+
+  override protected def ensureOnAbnormal[T](effect: Task[T])(finalizer: => Task[Unit]): Task[T] = effect.onExit {
+    exit =>
+      if (exit.isSuccess) ZIO.unit else finalizer.orDie
```
Comment (ioaoue) [inline effects/zio/src/main/scalajvm/sttp/client4/httpclient/zio/HttpClientZioBackend.scala:80]: I'm not sure if it's correct to use `.orDie` here. I don't think users will expect that sending a request might result in a defect. Defects are often considered unrecoverable and propagate until someone catches them, and in some cases can cause the entire application to crash. Maybe in this case it would be better to just ignore the error?

Comment (adamw) [reply effects/zio/src/main/scalajvm/sttp/client4/httpclient/zio/HttpClientZioBackend.scala:80]: There's a `.resurrect` later on, but yeah, maybe ignoring here is fine

Comment (ioaoue) [reply effects/zio/src/main/scalajvm/sttp/client4/httpclient/zio/HttpClientZioBackend.scala]: Oh, sorry, I somehow didn't notice the `.resurrect` call

Comment (adamw) [reply effects/zio/src/main/scalajvm/sttp/client4/httpclient/zio/HttpClientZioBackend.scala]: I change it to a log :)
