### PR TITLE
Don't close the effect system executor, if it is the one used by HttpClient. Only close thread-pool based executors.

### LINKED ISSUE #1686: HttpClientBackend throws `ClassCastException` on shutdown after update from 3.8.5 to 3.8.6
The following exception is being thrown after update from `3.8.5` to `3.8.6` (both using newest CE `3.4.4`):
```
java.lang.ClassCastException: class cats.effect.unsafe.WorkStealingThreadPool cannot be cast to class java.util.concurrent.ThreadPoolExecutor (cats.effect.unsafe.WorkStealingThreadPool is in unnamed module of loader 'app'; java.util.concurrent.ThreadPoolExecutor is in module java.base of loader 'bootstrap')
	at sttp.client3.HttpClientBackend$$anon$1.apply(HttpClientBackend.scala:108)
	at sttp.client3.HttpClientBackend$$anon$1.apply(HttpClientBackend.scala:107)
	at java.base/java.util.Optional.map(Optional.java:260)
	at sttp.client3.HttpClientBackend.$anonfun$close$1(HttpClientBackend.scala:107)
	at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
	at main$ @ com.superfund.exchange.webapi.user.WebApiUserNode$.main(WebApiUserNode.scala:8)
```
Diff between the versions: https://github.com/softwaremill/sttp/compare/v3.8.5...v3.8.6

### PR DESCRIPTION
**Pull request by adamw**
Closes #1686

### CODE REVIEW

**Review by ybasket — APPROVED** [review]
Thank you for fixing, seems as my testing setup for the executor feature was too limited for this bug, sorry.

File: core/src/main/scalajvm/sttp/client3/HttpClientBackend.scala [hunk 1]
```diff
@@ -105,7 +108,9 @@ abstract class HttpClientBackend[F[_], S, P, B](
         client
           .executor()
           .map[Unit](new function.Function[Executor, Unit] {
-            override def apply(t: Executor): Unit = t.asInstanceOf[ThreadPoolExecutor].shutdown()
+            override def apply(t: Executor): Unit = t match {
+              case tpe: ThreadPoolExecutor => tpe.shutdown()
```
Comment (ybasket) [inline core/src/main/scalajvm/sttp/client3/HttpClientBackend.scala:112]:
```suggestion
              case tpe: ThreadPoolExecutor => tpe.shutdown()
              case _ => ()
```

**Comment by adamw** [comment]
@ybasket no worries, happens. There was no  test, so we didn't spot this. There is one now ;)
